"""initial schema

Revision ID: 4d82795c4ce4
Revises: 
Create Date: 2026-04-18 13:41:37.948169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d82795c4ce4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('producer', 'admin', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crop_type', sa.Enum('vine', 'peach', name='croptype'), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('irrigation_type', sa.Enum('drip', 'sprinkler', 'flood', name='irrigationtype'), nullable=False),
    sa.Column('soil_type', sa.Enum('sandy', 'clay', 'loamy', name='soiltype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='fieldstatus'), nullable=False),
    sa.Column('polygon_geojson', sa.JSON(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('has_hail_net', sa.Boolean(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_user_id'), 'fields', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('frost', 'hail', 'heat_wave', 'critical_deficit', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_field_id'), 'alerts', ['field_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eto_mm', sa.Float(), nullable=False),
    sa.Column('kc', sa.Float(), nullable=False),
    sa.Column('kc_source', sa.Enum('s2_dynamic', 'tabular', name='kcsource'), nullable=False),
    sa.Column('etc_mm', sa.Float(), nullable=False),
    sa.Column('water_deficit_mm', sa.Float(), nullable=False),
    sa.Column('ks', sa.Float(), nullable=False),
    sa.Column('phenological_stage', sa.Enum('initial', 'development', 'mid', 'late', name='phenologicalstage'), nullable=False),
    sa.Column('recommended_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencylevel'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidencelevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_field_id'), 'recommendations', ['field_id'], unique=False)
    op.create_table('satellite_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('sentinel2', 'sentinel1', name='satellitesource'), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('ndwi', sa.Float(), nullable=False),
    sa.Column('evi', sa.Float(), nullable=False),
    sa.Column('backscatter_vv', sa.Float(), nullable=True),
    sa.Column('backscatter_vh', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=False),
    sa.Column('moisture_event_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_records_field_id'), 'satellite_records', ['field_id'], unique=False)
    op.create_table('soils',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('field_capacity', sa.Float(), nullable=False),
    sa.Column('wilting_point', sa.Float(), nullable=False),
    sa.Column('bulk_density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soils_field_id'), 'soils', ['field_id'], unique=True)
    op.create_table('irrigation_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('irrigation_date', sa.Date(), nullable=False),
    sa.Column('applied_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_confirmations_field_id'), 'irrigation_confirmations', ['field_id'], unique=False)
    op.create_index(op.f('ix_irrigation_confirmations_recommendation_id'), 'irrigation_confirmations', ['recommendation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_confirmations_recommendation_id'), table_name='irrigation_confirmations')
    op.drop_index(op.f('ix_irrigation_confirmations_field_id'), table_name='irrigation_confirmations')
    op.drop_table('irrigation_confirmations')
    op.drop_index(op.f('ix_soils_field_id'), table_name='soils')
    op.drop_table('soils')
    op.drop_index(op.f('ix_satellite_records_field_id'), table_name='satellite_records')
    op.drop_table('satellite_records')
    op.drop_index(op.f('ix_recommendations_field_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_alerts_field_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_fields_user_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
