"""clima diario en daily_water_balance

Revision ID: 53a8c7243f13
Revises: 8914fb7cdfba
Create Date: 2026-06-13 18:28:08.017860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a8c7243f13'
down_revision: Union[str, None] = '8914fb7cdfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_water_balances', sa.Column('temp_max_c', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('temp_min_c', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('temp_mean_c', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('humidity_pct', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('wind_speed_ms', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('solar_radiation_mj', sa.Float(), nullable=True))
    op.add_column('daily_water_balances', sa.Column('pressure_kpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_water_balances', 'pressure_kpa')
    op.drop_column('daily_water_balances', 'solar_radiation_mj')
    op.drop_column('daily_water_balances', 'wind_speed_ms')
    op.drop_column('daily_water_balances', 'humidity_pct')
    op.drop_column('daily_water_balances', 'temp_mean_c')
    op.drop_column('daily_water_balances', 'temp_min_c')
    op.drop_column('daily_water_balances', 'temp_max_c')
    # ### end Alembic commands ###
