"""add_last_deficit_to_fields

Revision ID: 5f8a939f9f8c
Revises: 6b832e9e48c0
Create Date: 2026-04-23 19:34:10.180290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8a939f9f8c'
down_revision: Union[str, None] = '6b832e9e48c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('last_deficit_mm', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('last_deficit_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'last_deficit_date')
    op.drop_column('fields', 'last_deficit_mm')
    # ### end Alembic commands ###
