"""add_alfalfa_to_crop_type

Revision ID: 6b832e9e48c0
Revises: 33211ac5caf3
Create Date: 2026-04-22 17:58:57.574489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b832e9e48c0'
down_revision: Union[str, None] = '33211ac5caf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
