"""flow_rate_ls_ha nullable

Revision ID: 8914fb7cdfba
Revises: b58f8d6c73ce
Create Date: 2026-06-01 16:14:05.434519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8914fb7cdfba'
down_revision: Union[str, None] = 'b58f8d6c73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sectors', 'flow_rate_ls_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sectors', 'flow_rate_ls_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
