"""add push_subscriptions table

Revision ID: a1202d91bd7f
Revises: f0e4e39f0eb3
Create Date: 2026-04-26 12:08:01.634224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1202d91bd7f'
down_revision: Union[str, None] = 'f0e4e39f0eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
