"""initial schema with sectors

Revision ID: a54f22feb24e
Revises: 
Create Date: 2026-05-30 19:42:18.928976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54f22feb24e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('producer', 'admin', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('soil_type', sa.Enum('sand', 'loamy_sand', 'sandy_loam', 'sandy_clay_loam', 'loam', 'silt_loam', 'silt', 'clay_loam', 'silty_clay_loam', 'sandy_clay', 'silty_clay', 'clay', name='soiltype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='fieldstatus'), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_user_id'), 'fields', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('frost', 'heat_wave', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_field_id'), 'alerts', ['field_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crop_type', sa.Enum('vine', 'peach', name='croptype'), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('polygon_geojson', sa.JSON(), nullable=True),
    sa.Column('irrigation_type', sa.Enum('aspersion', 'superficial', name='irrigationtype'), nullable=False),
    sa.Column('flow_rate_ls_ha', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('hail_net_type', sa.Enum('none', 'open', 'dense', 'color', name='hailnettype'), nullable=False),
    sa.Column('notification_frequency_days', sa.Integer(), nullable=False),
    sa.Column('notification_hour', sa.Time(), nullable=True),
    sa.Column('last_notification_date', sa.Date(), nullable=True),
    sa.Column('last_saturation_date', sa.Date(), nullable=True),
    sa.Column('last_deficit_mm', sa.Float(), nullable=True),
    sa.Column('last_deficit_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_field_id'), 'sectors', ['field_id'], unique=False)
    op.create_table('daily_water_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eto_mm', sa.Float(), nullable=False),
    sa.Column('kc', sa.Float(), nullable=False),
    sa.Column('kc_source', sa.Enum('s2_dynamic', 'tabular', name='kcsource'), nullable=False),
    sa.Column('etc_mm', sa.Float(), nullable=False),
    sa.Column('water_deficit_mm', sa.Float(), nullable=False),
    sa.Column('ks', sa.Float(), nullable=False),
    sa.Column('phenological_stage', sa.Enum('initial', 'development', 'mid', 'late', 'dormancy', name='phenologicalstage'), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('taw_mm', sa.Float(), nullable=False),
    sa.Column('raw_mm', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndvi_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'date', name='uq_balance_sector_date')
    )
    op.create_index(op.f('ix_daily_water_balances_sector_id'), 'daily_water_balances', ['sector_id'], unique=False)
    op.create_table('satellite_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=False),
    sa.Column('thumbnail_png', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_records_sector_id'), 'satellite_records', ['sector_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('water_balance_id', sa.Integer(), nullable=False),
    sa.Column('recommended_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencylevel'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidencelevel'), nullable=False),
    sa.Column('water_deficit_mm', sa.Float(), nullable=True),
    sa.Column('ks', sa.Float(), nullable=True),
    sa.Column('taw_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['water_balance_id'], ['daily_water_balances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_water_balance_id'), 'recommendations', ['water_balance_id'], unique=True)
    op.create_table('irrigation_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('irrigation_date', sa.Date(), nullable=False),
    sa.Column('applied_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_confirmations_recommendation_id'), 'irrigation_confirmations', ['recommendation_id'], unique=True)
    op.create_index(op.f('ix_irrigation_confirmations_sector_id'), 'irrigation_confirmations', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_confirmations_sector_id'), table_name='irrigation_confirmations')
    op.drop_index(op.f('ix_irrigation_confirmations_recommendation_id'), table_name='irrigation_confirmations')
    op.drop_table('irrigation_confirmations')
    op.drop_index(op.f('ix_recommendations_water_balance_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_satellite_records_sector_id'), table_name='satellite_records')
    op.drop_table('satellite_records')
    op.drop_index(op.f('ix_daily_water_balances_sector_id'), table_name='daily_water_balances')
    op.drop_table('daily_water_balances')
    op.drop_index(op.f('ix_sectors_field_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_alerts_field_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_fields_user_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
