"""add taw raw ndvi to recommendations

Revision ID: b7a7d032f86e
Revises: b73fb5e254c7
Create Date: 2026-04-27 19:28:52.670454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a7d032f86e'
down_revision: Union[str, None] = 'b73fb5e254c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('taw_mm', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('raw_mm', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('ndvi', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('ndvi_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'ndvi_date')
    op.drop_column('recommendations', 'ndvi')
    op.drop_column('recommendations', 'raw_mm')
    op.drop_column('recommendations', 'taw_mm')
    # ### end Alembic commands ###
