"""drop_soils_table

Revision ID: d7dcfd0fb018
Revises: b2c3d4e5f6a7
Create Date: 2026-05-12 10:42:16.940259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7dcfd0fb018'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soils_field_id'), table_name='soils')
    op.drop_table('soils')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soils',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wilting_point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bulk_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('soils_field_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('soils_pkey'))
    )
    op.create_index(op.f('ix_soils_field_id'), 'soils', ['field_id'], unique=True)
    # ### end Alembic commands ###
