"""add push_subscriptions table

Revision ID: f0e4e39f0eb3
Revises: 5f8a939f9f8c
Create Date: 2026-04-26 11:15:47.307017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e4e39f0eb3'
down_revision: Union[str, None] = '5f8a939f9f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
